### ISSUE TITLE
model test

### ISSUE THREAD

**Issue by shawrby** [andreasbinder/Point-GNN-PyTorch#1]
First of all, thank you for your contribution!

How can I test your model?

**Comment by andreasbinder** [comment]
Hi! I will update the repository this weekend!

**Comment by MaxistheSpy** [comment]
> Hi! I will update the repository this weekend!

does the model work, or is this project abandoned? Im looking into working with PointGNN and wanted a pytorch gemoetric version to work with, are there any instructions/readme?

**Comment by andreasbinder** [comment]
Hi @MaxistheSpy! Yes, this version is working 
I updated the model that I am using [here](https://github.com/andreasbinder/Point-GNN-PyTorch/blob/main/src/point_gnn_pytorch/models.py). 

@shawrby it expects the standard batch input from PyTorch-geometric:
```
import torch
from torch_geometric.data import Data, Batch

model = PointGNN_Normalization()

data_list = [Data(x=torch.tensor([[-1], [0], [1]], dtype=torch.float), 
            edge_index=torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]], dtype=torch.long))]

batch = Batch.from_data_list(data_list)

out = model(batch)
``` 
Does that work for you? 
Let me know if you encounter any problems! Note: if you just want to use the message passing layer, I released it to PyTorch-Geometric [here](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.conv.PointGNNConv.html#torch_geometric.nn.conv.PointGNNConv)
I am sorry for the late reply!
