### ISSUE TITLE
How to train the model on KITTI 3D detection dataset and submit the results to KITTI?

### ISSUE THREAD

**Issue by ZhenhuiTang** [andreasbinder/Point-GNN-PyTorch#2]

**Comment by andreasbinder** [comment]
Hi! [Here](https://github.com/andreasbinder/Point-GNN-PyTorch/blob/84e4ae9a375cfc914c5024e2a7693098a1addf4a/src/point_gnn_pytorch/models.py#L80) you can find the input parameters.

I suspect `num_node_features` will stay the same, you might need to adjust the number of output features `num_classes`.

Other than that you can instantiate it as any other PyG model. Hope it helps!
